#### Numpy

*Numpy is core data science library for mathematical/scientifiacal computuing in python.It provides a high performance 
multi-dimensonal array object and for working with arrays.

*Numpy provides fast built-in object (nd-array)

In [1]:
import numpy as np
arr=np.array([0,1,2,3,4,5,6,7,8]) #create a rank 1 numpy array
display(arr) #to display array
print(type(arr))
#<class 'numpy.array'>

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

<class 'numpy.ndarray'>


In [2]:
arr.dtype

dtype('int32')

In [3]:
arr.itemsize

4

In [4]:
arr.shape

(9,)

In [5]:
arr.nbytes

36

#### Array operations

simple math operations

In [6]:
a=np.array([10,20,30,40,50,60,70])
b=np.array([1,2,3,4,5,6,7])

#element addition or substraction
print(a+b)
print(a-b)

[11 22 33 44 55 66 77]
[ 9 18 27 36 45 54 63]


In [7]:
#Return evenly space values within give intervals
#create array from 0 to 10
#arrange(start,stop,step size)
np.arange(0,10,1)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
#start,stop,step
np.arange(1,16,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15])

#1.Why numpy array are better than list

In [9]:
import time
import numpy as np
array_size = 1000000
def python_version():   
    #start time
    t1 = time.time()
    x = range(array_size)
    y = range(array_size)
    
    #element by element addition
    z = [ x[i] + y[i] for i in range(len(x))]
    return time.time() - t1   #time.time return current time stmap value
def numpy_version():
    #start time
    t1 = time.time()
    x = np.arange(array_size)
    y = np.arange(array_size)
    z = x + y
    return time.time() - t1
t1 = python_version()
t2 = numpy_version()
print("Numpy in this example is : " +str(t1/t2) + " Faster")

Numpy in this example is : 74.65371024734982 Faster


In [10]:
distance_list=[10,15,18,19,21,23]
time_list=[.20,.43,.55,1.1,.59,1.2]
speed=distance_list/time_list
speed

TypeError: unsupported operand type(s) for /: 'list' and 'list'

In [12]:
distance_arr=np.array([10,15,18,19,21,23])
time_arr=np.array([.20,.43,.55,1.1,.59,1.2])
speed_arr=distance_arr/time_arr
speed_arr

array([50.        , 34.88372093, 32.72727273, 17.27272727, 35.59322034,
       19.16666667])

#### Types of numpy array

In [13]:
#create a 1-D array
arr_1=np.array([10,15,18,19,21,25])

In [22]:
#create a  2-D array
arr_2=np.array([[1,5,8,9,11,18],[10,15,18,19,21,25]])
arr_2

array([[ 1,  5,  8,  9, 11, 18],
       [10, 15, 18, 19, 21, 25]])

In [23]:
arr_2.shape

(2, 6)

In [24]:
arr_2.dtype

dtype('int32')

In [25]:
arr_2.ndim

2

In [27]:
arr_2[1][4]

21

In [28]:
arr_2[-1][-2]

21

#### 3 Dimensional arra

In [30]:
arr_3=np.array([[[1,5,8,9,11,18],[10,15,18,19,21,25],[11,12,13,14,15,16]],
               [[1,5,8,9,11,18],[10,15,18,19,21,25],[11,12,13,14,15,16]],
              [[1,5,8,9,11,18],[10,15,18,19,21,25],[11,12,13,14,15,16]]])
print(arr_3)

[[[ 1  5  8  9 11 18]
  [10 15 18 19 21 25]
  [11 12 13 14 15 16]]

 [[ 1  5  8  9 11 18]
  [10 15 18 19 21 25]
  [11 12 13 14 15 16]]

 [[ 1  5  8  9 11 18]
  [10 15 18 19 21 25]
  [11 12 13 14 15 16]]]


In [31]:
arr_3.shape

(3, 3, 6)

In [32]:
arr_3.dtype

dtype('int32')

In [33]:
arr_3.ndim

3

In [34]:
print(arr_3[1][2][4])
print(arr_3[1,2,4])

15
15


In [35]:
arr_4=np.array([11,23,34,45,56,67,78])
arr_4.dtype

dtype('int32')

In [36]:
#assigning float to int32 array, it will truncate the decimal part
arr_4[1]=14.5678
print(arr_4)

[11 14 34 45 56 67 78]


In [39]:
#change dtype of array to float
arr_5=arr_4.astype('float32')
arr_5[1]=14.5678
print(arr_5)

[11.     14.5678 34.     45.     56.     67.     78.    ]
